ALTER TABLE posts ADD COLUMN IF NOT EXISTS approved   BOOLEAN DEFAULT true;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS likes      INT     DEFAULT 0;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS hits       INT     DEFAULT 0;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS card_image TEXT;
